[package]
name = "symphony-types"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
ulid = { workspace = true, features = ["serde"] }

[build-dependencies]
prost-build = { workspace = true }
