[package]
name = "commons"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.3"
serde = { version = "1.0.228", features = ["derive"] }
ulid = { version = "1.2.1", features = ["serde"] }

[build-dependencies]
prost-build = "0.14.3"
